---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr?ref=v1.3.1
- https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=32d3d0e7e7dc754356c684a8eaad7a200a6d7093
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-k8s?ref=v1.3.1
- https://github.com/networkservicemesh/deployments-k8s/apps/admission-webhook-k8s?ref=32d3d0e7e7dc754356c684a8eaad7a200a6d7093
